spring:
  profiles:
    active: local

server:
  port : 7070

--- # local
spring:
  config:
    activate:
      on-profile: local
  profiles:
    include: secret-local

--- # prod
spring:
  config:
    activate:
      on-profile: prod
  profiles:
    include: secret-prod
