spring:
  profiles:
    group:
      default: local,secret-local
      prod: secret-prod
server:
  port: 7070

security:
  jwt:
    token:
      secret-key: Z29uZy1jaGVjay1nb25nLWNoZWNrLWdvbmctY2hlY2stZ29uZy1jaGVjay1nb25nLWNoZWNrLWdvbmctY2hlY2stZ29uZy1jaGVjay1nb25nLWNoZWNrCg==
      expire-time: 3600000

---
spring:
  config:
    activate:
      on-profile: local

file:
  upload-dir: images

---
spring:
  config:
    activate:
      on-profile: prod
file:
  upload-dir: /home/ubuntu/images
