spring:
  profiles:
    group:
      default: local,secret
      prod: prod,secret

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 8
      minimum-idle: 5
      idle-timeout: 600000
      validation-timeout: 5000
    username: sa
    password:

  sql:
    init:
      mode: always

server:
  port: 7070

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
---
spring:
  config:
    activate:
      on-profile: local

file:
  upload-dir: images

---
spring:
  config:
    activate:
      on-profile: prod
file:
  upload-dir: /home/ubuntu/images
