spring:
  profiles:
    group:
      default: local,secret
      prod: prod,secret

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:

  sql:
    init:
      mode: always

server:
  port: 7070

---
spring:
  config:
    activate:
      on-profile: local

file:
  upload-dir: images

---
spring:
  config:
    activate:
      on-profile: prod
file:
  upload-dir: /home/ubuntu/images
