FROM amazoncorretto:17

ARG VERSION
ENV VERSION $VERSION
ARG BUILD_TIMESTAMP
ENV BUILD_TIMESTAMP $BUILD_TIMESTAMP

LABEL maintainer="Jihun Hwang <goharrm@gmail.com>"
LABEL version="$VERSION"
LABEL description="build at $BUILD_TIMESTAMP"

EXPOSE 7070
VOLUME ["/var/log"]

ARG JAR_FILE=/build/libs/offer-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} /offer-dev-app.jar

USER root
WORKDIR /

# TimeZone correction
RUN echo "Asia/Seoul" > /etc/timezone

ENTRYPOINT ["java","-jar","/offer-dev-app.jar"]
# ENTRYPOINT ["java","-jar","-Dspring.config.location=/spring-run-env/application-dev.yml","/offer-dev-app.jar"]
