name: Deploy to Dev Server

on:
  push:
    branches: [ "cicd-test" ]

permissions:
  contents: read

env:
  DOCKER_FILE: docker/Dockerfile-dev

jobs:
  build_and_deploy_to_dev:

    runs-on: ubuntu-latest

    steps:
      ## checkout and setup jdk
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      ## Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      ## gradle build without test jar
      - name: Build with Gradle
        run: ./gradlew clean build # -x test
        shell: bash

      ## docker build & push to hub
      - name: Process CD
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          
          REPO_OFFER_DEV=${{ secrets.DOCKER_USERNAME }}/offer-dev
          
          chmod +x ./scripts/build_docker.sh
          ./scripts/build_docker.sh ${REPO_OFFER_DEV} ${DOCKER_FILE} ${{ secrets.GIT_USER_EMAIL }} ${{ secrets.GIT_USER_NAME }}